title: Hello Nerves. Getting Started with the Raspberry Pi and Nerves.
author: Matt
description: >
  Getting started using Nerves with the Raspberry Pi

twitter_username: ohrwurmat
github_username: theendisnear

show_excerpts: true

exclude: [README.md]
timezone: America/Denver

theme: jekyll-theme-midnight
